// ╔══════════════════════════════════════════════════════════════════╗
// ║ AUTO-GENERATED from data/rebase_bairoch.txt. Do not edit.        ║
// ║ Regenerate with:                                                 ║
// ║   cargo run -p seqforge-restriction --bin codegen                ║
// ║                                                                   ║
// ║ Source: REBASE — The Restriction Enzyme Database                 ║
// ║   http://rebase.neb.com                                          ║
// ║   Copyright (c) Dr. Richard J. Roberts. Used with attribution.   ║
// ╚══════════════════════════════════════════════════════════════════╝

use crate::enzyme::{Enzyme, EnzymeType, Iupac};

pub const ENZYMES: &[Enzyme] = &[
    Enzyme { name: "AanI", recognition: &[Iupac::T, Iupac::T, Iupac::A, Iupac::T, Iupac::A, Iupac::A], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AarI", recognition: &[Iupac::C, Iupac::A, Iupac::C, Iupac::C, Iupac::T, Iupac::G, Iupac::C], top_offset: 11, bottom_offset: 15, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "AatII", recognition: &[Iupac::G, Iupac::A, Iupac::C, Iupac::G, Iupac::T, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AbsI", recognition: &[Iupac::C, Iupac::C, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::G, Iupac::G], top_offset: 2, bottom_offset: 6, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Acc16I", recognition: &[Iupac::T, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::A], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Acc36I", recognition: &[Iupac::A, Iupac::C, Iupac::C, Iupac::T, Iupac::G, Iupac::C], top_offset: 10, bottom_offset: 14, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "Acc65I", recognition: &[Iupac::G, Iupac::G, Iupac::T, Iupac::A, Iupac::C, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AccB1I", recognition: &[Iupac::G, Iupac::G, Iupac::Y, Iupac::R, Iupac::C, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AccB7I", recognition: &[Iupac::C, Iupac::C, Iupac::A, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::T, Iupac::G, Iupac::G], top_offset: 7, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AccBSI", recognition: &[Iupac::C, Iupac::C, Iupac::G, Iupac::C, Iupac::T, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "AccI", recognition: &[Iupac::G, Iupac::T, Iupac::M, Iupac::K, Iupac::A, Iupac::C], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AccII", recognition: &[Iupac::C, Iupac::G, Iupac::C, Iupac::G], top_offset: 2, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AccIII", recognition: &[Iupac::T, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::A], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AciI", recognition: &[Iupac::C, Iupac::C, Iupac::G, Iupac::C], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "AclI", recognition: &[Iupac::A, Iupac::A, Iupac::C, Iupac::G, Iupac::T, Iupac::T], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AclWI", recognition: &[Iupac::G, Iupac::G, Iupac::A, Iupac::T, Iupac::C], top_offset: 9, bottom_offset: 10, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "AcoI", recognition: &[Iupac::Y, Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::R], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AcsI", recognition: &[Iupac::R, Iupac::A, Iupac::A, Iupac::T, Iupac::T, Iupac::Y], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AcvI", recognition: &[Iupac::C, Iupac::A, Iupac::C, Iupac::G, Iupac::T, Iupac::G], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AcyI", recognition: &[Iupac::G, Iupac::R, Iupac::C, Iupac::G, Iupac::Y, Iupac::C], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AdeI", recognition: &[Iupac::C, Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::T, Iupac::G], top_offset: 6, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AfeI", recognition: &[Iupac::A, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::T], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AfiI", recognition: &[Iupac::C, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::G], top_offset: 7, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AflII", recognition: &[Iupac::C, Iupac::T, Iupac::T, Iupac::A, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AflIII", recognition: &[Iupac::A, Iupac::C, Iupac::R, Iupac::Y, Iupac::G, Iupac::T], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AgeI", recognition: &[Iupac::A, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::T], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AgsI", recognition: &[Iupac::T, Iupac::T, Iupac::S, Iupac::A, Iupac::A], top_offset: 3, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AhdI", recognition: &[Iupac::G, Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::T, Iupac::C], top_offset: 6, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AhlI", recognition: &[Iupac::A, Iupac::C, Iupac::T, Iupac::A, Iupac::G, Iupac::T], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AjiI", recognition: &[Iupac::C, Iupac::A, Iupac::C, Iupac::G, Iupac::T, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "AjnI", recognition: &[Iupac::C, Iupac::C, Iupac::W, Iupac::G, Iupac::G], top_offset: 0, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AjuI", recognition: &[Iupac::G, Iupac::A, Iupac::A, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::T, Iupac::T, Iupac::G, Iupac::G], top_offset: 25, bottom_offset: 20, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "AleI", recognition: &[Iupac::C, Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::T, Iupac::G], top_offset: 5, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AlfI", recognition: &[Iupac::G, Iupac::C, Iupac::A, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::T, Iupac::G, Iupac::C], top_offset: 24, bottom_offset: 22, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "AluBI", recognition: &[Iupac::A, Iupac::G, Iupac::C, Iupac::T], top_offset: 2, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AluI", recognition: &[Iupac::A, Iupac::G, Iupac::C, Iupac::T], top_offset: 2, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Alw21I", recognition: &[Iupac::G, Iupac::W, Iupac::G, Iupac::C, Iupac::W, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Alw26I", recognition: &[Iupac::G, Iupac::T, Iupac::C, Iupac::T, Iupac::C], top_offset: 6, bottom_offset: 10, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "Alw44I", recognition: &[Iupac::G, Iupac::T, Iupac::G, Iupac::C, Iupac::A, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AlwI", recognition: &[Iupac::G, Iupac::G, Iupac::A, Iupac::T, Iupac::C], top_offset: 9, bottom_offset: 10, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "AlwNI", recognition: &[Iupac::C, Iupac::A, Iupac::G, Iupac::N, Iupac::N, Iupac::N, Iupac::C, Iupac::T, Iupac::G], top_offset: 6, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Ama87I", recognition: &[Iupac::C, Iupac::Y, Iupac::C, Iupac::G, Iupac::R, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Aor13HI", recognition: &[Iupac::T, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::A], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "ApaI", recognition: &[Iupac::G, Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "ApaLI", recognition: &[Iupac::G, Iupac::T, Iupac::G, Iupac::C, Iupac::A, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "ApeKI", recognition: &[Iupac::G, Iupac::C, Iupac::W, Iupac::G, Iupac::C], top_offset: 1, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "ApoI", recognition: &[Iupac::R, Iupac::A, Iupac::A, Iupac::T, Iupac::T, Iupac::Y], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "ArsI", recognition: &[Iupac::G, Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::T, Iupac::T, Iupac::Y, Iupac::G], top_offset: 24, bottom_offset: 19, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "AscI", recognition: &[Iupac::G, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::C], top_offset: 2, bottom_offset: 6, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AseI", recognition: &[Iupac::A, Iupac::T, Iupac::T, Iupac::A, Iupac::A, Iupac::T], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AsiGI", recognition: &[Iupac::A, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::T], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AsiSI", recognition: &[Iupac::G, Iupac::C, Iupac::G, Iupac::A, Iupac::T, Iupac::C, Iupac::G, Iupac::C], top_offset: 5, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AspA2I", recognition: &[Iupac::C, Iupac::C, Iupac::T, Iupac::A, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AspEI", recognition: &[Iupac::G, Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::T, Iupac::C], top_offset: 6, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AspLEI", recognition: &[Iupac::G, Iupac::C, Iupac::G, Iupac::C], top_offset: 3, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AspS9I", recognition: &[Iupac::G, Iupac::G, Iupac::N, Iupac::C, Iupac::C], top_offset: 1, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AsuC2I", recognition: &[Iupac::C, Iupac::C, Iupac::S, Iupac::G, Iupac::G], top_offset: 2, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AsuHPI", recognition: &[Iupac::G, Iupac::G, Iupac::T, Iupac::G, Iupac::A], top_offset: 13, bottom_offset: 12, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "AsuII", recognition: &[Iupac::T, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::A], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AsuNHI", recognition: &[Iupac::G, Iupac::C, Iupac::T, Iupac::A, Iupac::G, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AvaI", recognition: &[Iupac::C, Iupac::Y, Iupac::C, Iupac::G, Iupac::R, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AvaII", recognition: &[Iupac::G, Iupac::G, Iupac::W, Iupac::C, Iupac::C], top_offset: 1, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AviII", recognition: &[Iupac::T, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::A], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AvrII", recognition: &[Iupac::C, Iupac::C, Iupac::T, Iupac::A, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "AxyI", recognition: &[Iupac::C, Iupac::C, Iupac::T, Iupac::N, Iupac::A, Iupac::G, Iupac::G], top_offset: 2, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BaeGI", recognition: &[Iupac::G, Iupac::K, Iupac::G, Iupac::C, Iupac::M, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BalI", recognition: &[Iupac::T, Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::A], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BamHI", recognition: &[Iupac::G, Iupac::G, Iupac::A, Iupac::T, Iupac::C, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BanI", recognition: &[Iupac::G, Iupac::G, Iupac::Y, Iupac::R, Iupac::C, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BanII", recognition: &[Iupac::G, Iupac::R, Iupac::G, Iupac::C, Iupac::Y, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BarI", recognition: &[Iupac::G, Iupac::A, Iupac::A, Iupac::G, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::T, Iupac::A, Iupac::C], top_offset: 25, bottom_offset: 20, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BauI", recognition: &[Iupac::C, Iupac::A, Iupac::C, Iupac::G, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BbrPI", recognition: &[Iupac::C, Iupac::A, Iupac::C, Iupac::G, Iupac::T, Iupac::G], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BbsI", recognition: &[Iupac::G, Iupac::A, Iupac::A, Iupac::G, Iupac::A, Iupac::C], top_offset: 8, bottom_offset: 12, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BbuI", recognition: &[Iupac::G, Iupac::C, Iupac::A, Iupac::T, Iupac::G, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bbv12I", recognition: &[Iupac::G, Iupac::W, Iupac::G, Iupac::C, Iupac::W, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BbvCI", recognition: &[Iupac::C, Iupac::C, Iupac::T, Iupac::C, Iupac::A, Iupac::G, Iupac::C], top_offset: 2, bottom_offset: 5, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BbvI", recognition: &[Iupac::G, Iupac::C, Iupac::A, Iupac::G, Iupac::C], top_offset: 13, bottom_offset: 17, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BccI", recognition: &[Iupac::C, Iupac::C, Iupac::A, Iupac::T, Iupac::C], top_offset: 9, bottom_offset: 10, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BceAI", recognition: &[Iupac::A, Iupac::C, Iupac::G, Iupac::G, Iupac::C], top_offset: 17, bottom_offset: 19, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BciVI", recognition: &[Iupac::G, Iupac::T, Iupac::A, Iupac::T, Iupac::C, Iupac::C], top_offset: 12, bottom_offset: 11, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BclI", recognition: &[Iupac::T, Iupac::G, Iupac::A, Iupac::T, Iupac::C, Iupac::A], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BcnI", recognition: &[Iupac::C, Iupac::C, Iupac::S, Iupac::G, Iupac::G], top_offset: 2, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BcoDI", recognition: &[Iupac::G, Iupac::T, Iupac::C, Iupac::T, Iupac::C], top_offset: 6, bottom_offset: 10, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BcuI", recognition: &[Iupac::A, Iupac::C, Iupac::T, Iupac::A, Iupac::G, Iupac::T], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BfaI", recognition: &[Iupac::C, Iupac::T, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BfmI", recognition: &[Iupac::C, Iupac::T, Iupac::R, Iupac::Y, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BfuAI", recognition: &[Iupac::A, Iupac::C, Iupac::C, Iupac::T, Iupac::G, Iupac::C], top_offset: 10, bottom_offset: 14, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BfuI", recognition: &[Iupac::G, Iupac::T, Iupac::A, Iupac::T, Iupac::C, Iupac::C], top_offset: 12, bottom_offset: 11, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BglI", recognition: &[Iupac::G, Iupac::C, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::G, Iupac::C], top_offset: 7, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BglII", recognition: &[Iupac::A, Iupac::G, Iupac::A, Iupac::T, Iupac::C, Iupac::T], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BlpI", recognition: &[Iupac::G, Iupac::C, Iupac::T, Iupac::N, Iupac::A, Iupac::G, Iupac::C], top_offset: 2, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BmcAI", recognition: &[Iupac::A, Iupac::G, Iupac::T, Iupac::A, Iupac::C, Iupac::T], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bme1390I", recognition: &[Iupac::C, Iupac::C, Iupac::N, Iupac::G, Iupac::G], top_offset: 2, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bme18I", recognition: &[Iupac::G, Iupac::G, Iupac::W, Iupac::C, Iupac::C], top_offset: 1, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BmeRI", recognition: &[Iupac::G, Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::T, Iupac::C], top_offset: 6, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BmgBI", recognition: &[Iupac::C, Iupac::A, Iupac::C, Iupac::G, Iupac::T, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BmiI", recognition: &[Iupac::G, Iupac::G, Iupac::N, Iupac::N, Iupac::C, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BmrFI", recognition: &[Iupac::C, Iupac::C, Iupac::N, Iupac::G, Iupac::G], top_offset: 2, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BmrI", recognition: &[Iupac::A, Iupac::C, Iupac::T, Iupac::G, Iupac::G, Iupac::G], top_offset: 11, bottom_offset: 10, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BmtI", recognition: &[Iupac::G, Iupac::C, Iupac::T, Iupac::A, Iupac::G, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BmuI", recognition: &[Iupac::A, Iupac::C, Iupac::T, Iupac::G, Iupac::G, Iupac::G], top_offset: 11, bottom_offset: 10, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BmyI", recognition: &[Iupac::G, Iupac::D, Iupac::G, Iupac::C, Iupac::H, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BoxI", recognition: &[Iupac::G, Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::T, Iupac::C], top_offset: 5, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BpiI", recognition: &[Iupac::G, Iupac::A, Iupac::A, Iupac::G, Iupac::A, Iupac::C], top_offset: 8, bottom_offset: 12, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BplI", recognition: &[Iupac::G, Iupac::A, Iupac::G, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::C, Iupac::T, Iupac::C], top_offset: 24, bottom_offset: 19, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "Bpu10I", recognition: &[Iupac::C, Iupac::C, Iupac::T, Iupac::N, Iupac::A, Iupac::G, Iupac::C], top_offset: 2, bottom_offset: 5, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "Bpu1102I", recognition: &[Iupac::G, Iupac::C, Iupac::T, Iupac::N, Iupac::A, Iupac::G, Iupac::C], top_offset: 2, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bpu14I", recognition: &[Iupac::T, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::A], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BpuMI", recognition: &[Iupac::C, Iupac::C, Iupac::S, Iupac::G, Iupac::G], top_offset: 2, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bsa29I", recognition: &[Iupac::A, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::T], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BsaAI", recognition: &[Iupac::Y, Iupac::A, Iupac::C, Iupac::G, Iupac::T, Iupac::R], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BsaBI", recognition: &[Iupac::G, Iupac::A, Iupac::T, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::A, Iupac::T, Iupac::C], top_offset: 5, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BsaHI", recognition: &[Iupac::G, Iupac::R, Iupac::C, Iupac::G, Iupac::Y, Iupac::C], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BsaI", recognition: &[Iupac::G, Iupac::G, Iupac::T, Iupac::C, Iupac::T, Iupac::C], top_offset: 7, bottom_offset: 11, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BsaJI", recognition: &[Iupac::C, Iupac::C, Iupac::N, Iupac::N, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BsaMI", recognition: &[Iupac::G, Iupac::A, Iupac::A, Iupac::T, Iupac::G, Iupac::C], top_offset: 7, bottom_offset: 5, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BsaWI", recognition: &[Iupac::W, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::W], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BsaXI", recognition: &[Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::C, Iupac::T, Iupac::C, Iupac::C], top_offset: 21, bottom_offset: 18, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "Bsc4I", recognition: &[Iupac::C, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::G], top_offset: 7, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bse118I", recognition: &[Iupac::R, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::Y], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bse1I", recognition: &[Iupac::A, Iupac::C, Iupac::T, Iupac::G, Iupac::G], top_offset: 6, bottom_offset: 4, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "Bse21I", recognition: &[Iupac::C, Iupac::C, Iupac::T, Iupac::N, Iupac::A, Iupac::G, Iupac::G], top_offset: 2, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bse3DI", recognition: &[Iupac::G, Iupac::C, Iupac::A, Iupac::A, Iupac::T, Iupac::G], top_offset: 8, bottom_offset: 6, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "Bse8I", recognition: &[Iupac::G, Iupac::A, Iupac::T, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::A, Iupac::T, Iupac::C], top_offset: 5, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BseAI", recognition: &[Iupac::T, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::A], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BseBI", recognition: &[Iupac::C, Iupac::C, Iupac::W, Iupac::G, Iupac::G], top_offset: 2, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BseCI", recognition: &[Iupac::A, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::T], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BseDI", recognition: &[Iupac::C, Iupac::C, Iupac::N, Iupac::N, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BseGI", recognition: &[Iupac::G, Iupac::G, Iupac::A, Iupac::T, Iupac::G], top_offset: 7, bottom_offset: 5, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BseJI", recognition: &[Iupac::G, Iupac::A, Iupac::T, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::A, Iupac::T, Iupac::C], top_offset: 5, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BseLI", recognition: &[Iupac::C, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::G], top_offset: 7, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BseMI", recognition: &[Iupac::G, Iupac::C, Iupac::A, Iupac::A, Iupac::T, Iupac::G], top_offset: 8, bottom_offset: 6, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BseNI", recognition: &[Iupac::A, Iupac::C, Iupac::T, Iupac::G, Iupac::G], top_offset: 6, bottom_offset: 4, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BsePI", recognition: &[Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::G, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BseSI", recognition: &[Iupac::G, Iupac::K, Iupac::G, Iupac::C, Iupac::M, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BseX3I", recognition: &[Iupac::C, Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BseXI", recognition: &[Iupac::G, Iupac::C, Iupac::A, Iupac::G, Iupac::C], top_offset: 13, bottom_offset: 17, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BseYI", recognition: &[Iupac::C, Iupac::C, Iupac::C, Iupac::A, Iupac::G, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "Bsh1236I", recognition: &[Iupac::C, Iupac::G, Iupac::C, Iupac::G], top_offset: 2, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bsh1285I", recognition: &[Iupac::C, Iupac::G, Iupac::R, Iupac::Y, Iupac::C, Iupac::G], top_offset: 4, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BshFI", recognition: &[Iupac::G, Iupac::G, Iupac::C, Iupac::C], top_offset: 2, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BshNI", recognition: &[Iupac::G, Iupac::G, Iupac::Y, Iupac::R, Iupac::C, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BshTI", recognition: &[Iupac::A, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::T], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BshVI", recognition: &[Iupac::A, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::T], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BsiEI", recognition: &[Iupac::C, Iupac::G, Iupac::R, Iupac::Y, Iupac::C, Iupac::G], top_offset: 4, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BsiHKAI", recognition: &[Iupac::G, Iupac::W, Iupac::G, Iupac::C, Iupac::W, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BsiHKCI", recognition: &[Iupac::C, Iupac::Y, Iupac::C, Iupac::G, Iupac::R, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BsiSI", recognition: &[Iupac::C, Iupac::C, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BsiWI", recognition: &[Iupac::C, Iupac::G, Iupac::T, Iupac::A, Iupac::C, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BslFI", recognition: &[Iupac::G, Iupac::G, Iupac::G, Iupac::A, Iupac::C], top_offset: 15, bottom_offset: 19, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BslI", recognition: &[Iupac::C, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::G], top_offset: 7, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BsmAI", recognition: &[Iupac::G, Iupac::T, Iupac::C, Iupac::T, Iupac::C], top_offset: 6, bottom_offset: 10, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BsmBI", recognition: &[Iupac::C, Iupac::G, Iupac::T, Iupac::C, Iupac::T, Iupac::C], top_offset: 7, bottom_offset: 11, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BsmI", recognition: &[Iupac::G, Iupac::A, Iupac::A, Iupac::T, Iupac::G, Iupac::C], top_offset: 7, bottom_offset: 5, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BsnI", recognition: &[Iupac::G, Iupac::G, Iupac::C, Iupac::C], top_offset: 2, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bso31I", recognition: &[Iupac::G, Iupac::G, Iupac::T, Iupac::C, Iupac::T, Iupac::C], top_offset: 7, bottom_offset: 11, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BsoBI", recognition: &[Iupac::C, Iupac::Y, Iupac::C, Iupac::G, Iupac::R, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bsp119I", recognition: &[Iupac::T, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::A], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bsp120I", recognition: &[Iupac::G, Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bsp1286I", recognition: &[Iupac::G, Iupac::D, Iupac::G, Iupac::C, Iupac::H, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bsp13I", recognition: &[Iupac::T, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::A], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bsp1407I", recognition: &[Iupac::T, Iupac::G, Iupac::T, Iupac::A, Iupac::C, Iupac::A], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bsp143I", recognition: &[Iupac::G, Iupac::A, Iupac::T, Iupac::C], top_offset: 0, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bsp1720I", recognition: &[Iupac::G, Iupac::C, Iupac::T, Iupac::N, Iupac::A, Iupac::G, Iupac::C], top_offset: 2, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bsp19I", recognition: &[Iupac::C, Iupac::C, Iupac::A, Iupac::T, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bsp68I", recognition: &[Iupac::T, Iupac::C, Iupac::G, Iupac::C, Iupac::G, Iupac::A], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BspACI", recognition: &[Iupac::C, Iupac::C, Iupac::G, Iupac::C], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BspDI", recognition: &[Iupac::A, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::T], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BspEI", recognition: &[Iupac::T, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::A], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BspFNI", recognition: &[Iupac::C, Iupac::G, Iupac::C, Iupac::G], top_offset: 2, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BspHI", recognition: &[Iupac::T, Iupac::C, Iupac::A, Iupac::T, Iupac::G, Iupac::A], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BspLI", recognition: &[Iupac::G, Iupac::G, Iupac::N, Iupac::N, Iupac::C, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BspMI", recognition: &[Iupac::A, Iupac::C, Iupac::C, Iupac::T, Iupac::G, Iupac::C], top_offset: 10, bottom_offset: 14, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BspOI", recognition: &[Iupac::G, Iupac::C, Iupac::T, Iupac::A, Iupac::G, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BspPI", recognition: &[Iupac::G, Iupac::G, Iupac::A, Iupac::T, Iupac::C], top_offset: 9, bottom_offset: 10, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BspQI", recognition: &[Iupac::G, Iupac::C, Iupac::T, Iupac::C, Iupac::T, Iupac::T, Iupac::C], top_offset: 8, bottom_offset: 11, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BspTI", recognition: &[Iupac::C, Iupac::T, Iupac::T, Iupac::A, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BsrBI", recognition: &[Iupac::C, Iupac::C, Iupac::G, Iupac::C, Iupac::T, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BsrDI", recognition: &[Iupac::G, Iupac::C, Iupac::A, Iupac::A, Iupac::T, Iupac::G], top_offset: 8, bottom_offset: 6, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BsrFI", recognition: &[Iupac::R, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::Y], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BsrGI", recognition: &[Iupac::T, Iupac::G, Iupac::T, Iupac::A, Iupac::C, Iupac::A], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BsrI", recognition: &[Iupac::A, Iupac::C, Iupac::T, Iupac::G, Iupac::G], top_offset: 6, bottom_offset: 4, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BsrSI", recognition: &[Iupac::A, Iupac::C, Iupac::T, Iupac::G, Iupac::G], top_offset: 6, bottom_offset: 4, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BssAI", recognition: &[Iupac::R, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::Y], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BssECI", recognition: &[Iupac::C, Iupac::C, Iupac::N, Iupac::N, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BssHII", recognition: &[Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::G, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BssMI", recognition: &[Iupac::G, Iupac::A, Iupac::T, Iupac::C], top_offset: 0, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BssNAI", recognition: &[Iupac::G, Iupac::T, Iupac::A, Iupac::T, Iupac::A, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BssNI", recognition: &[Iupac::G, Iupac::R, Iupac::C, Iupac::G, Iupac::Y, Iupac::C], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BssSI", recognition: &[Iupac::C, Iupac::A, Iupac::C, Iupac::G, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BssT1I", recognition: &[Iupac::C, Iupac::C, Iupac::W, Iupac::W, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bst1107I", recognition: &[Iupac::G, Iupac::T, Iupac::A, Iupac::T, Iupac::A, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bst2BI", recognition: &[Iupac::C, Iupac::A, Iupac::C, Iupac::G, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "Bst2UI", recognition: &[Iupac::C, Iupac::C, Iupac::W, Iupac::G, Iupac::G], top_offset: 2, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bst4CI", recognition: &[Iupac::A, Iupac::C, Iupac::N, Iupac::G, Iupac::T], top_offset: 3, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bst6I", recognition: &[Iupac::C, Iupac::T, Iupac::C, Iupac::T, Iupac::T, Iupac::C], top_offset: 7, bottom_offset: 10, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "Bst98I", recognition: &[Iupac::C, Iupac::T, Iupac::T, Iupac::A, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstACI", recognition: &[Iupac::G, Iupac::R, Iupac::C, Iupac::G, Iupac::Y, Iupac::C], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstAFI", recognition: &[Iupac::C, Iupac::T, Iupac::T, Iupac::A, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstAPI", recognition: &[Iupac::G, Iupac::C, Iupac::A, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::T, Iupac::G, Iupac::C], top_offset: 7, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstAUI", recognition: &[Iupac::T, Iupac::G, Iupac::T, Iupac::A, Iupac::C, Iupac::A], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstBAI", recognition: &[Iupac::Y, Iupac::A, Iupac::C, Iupac::G, Iupac::T, Iupac::R], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstBI", recognition: &[Iupac::T, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::A], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstC8I", recognition: &[Iupac::G, Iupac::C, Iupac::N, Iupac::N, Iupac::G, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstDEI", recognition: &[Iupac::C, Iupac::T, Iupac::N, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstDSI", recognition: &[Iupac::C, Iupac::C, Iupac::R, Iupac::Y, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstEII", recognition: &[Iupac::G, Iupac::G, Iupac::T, Iupac::N, Iupac::A, Iupac::C, Iupac::C], top_offset: 1, bottom_offset: 6, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstENI", recognition: &[Iupac::C, Iupac::C, Iupac::T, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::A, Iupac::G, Iupac::G], top_offset: 5, bottom_offset: 6, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstF5I", recognition: &[Iupac::G, Iupac::G, Iupac::A, Iupac::T, Iupac::G], top_offset: 7, bottom_offset: 5, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BstFI", recognition: &[Iupac::A, Iupac::A, Iupac::G, Iupac::C, Iupac::T, Iupac::T], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstFNI", recognition: &[Iupac::C, Iupac::G, Iupac::C, Iupac::G], top_offset: 2, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstH2I", recognition: &[Iupac::R, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::Y], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstHHI", recognition: &[Iupac::G, Iupac::C, Iupac::G, Iupac::C], top_offset: 3, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstKTI", recognition: &[Iupac::G, Iupac::A, Iupac::T, Iupac::C], top_offset: 3, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstMAI", recognition: &[Iupac::G, Iupac::T, Iupac::C, Iupac::T, Iupac::C], top_offset: 6, bottom_offset: 10, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BstMBI", recognition: &[Iupac::G, Iupac::A, Iupac::T, Iupac::C], top_offset: 0, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstMCI", recognition: &[Iupac::C, Iupac::G, Iupac::R, Iupac::Y, Iupac::C, Iupac::G], top_offset: 4, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstMWI", recognition: &[Iupac::G, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::C], top_offset: 7, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstNI", recognition: &[Iupac::C, Iupac::C, Iupac::W, Iupac::G, Iupac::G], top_offset: 2, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstNSI", recognition: &[Iupac::R, Iupac::C, Iupac::A, Iupac::T, Iupac::G, Iupac::Y], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstOI", recognition: &[Iupac::C, Iupac::C, Iupac::W, Iupac::G, Iupac::G], top_offset: 2, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstPAI", recognition: &[Iupac::G, Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::T, Iupac::C], top_offset: 5, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstSCI", recognition: &[Iupac::C, Iupac::C, Iupac::N, Iupac::G, Iupac::G], top_offset: 0, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstSFI", recognition: &[Iupac::C, Iupac::T, Iupac::R, Iupac::Y, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstSLI", recognition: &[Iupac::G, Iupac::K, Iupac::G, Iupac::C, Iupac::M, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstSNI", recognition: &[Iupac::T, Iupac::A, Iupac::C, Iupac::G, Iupac::T, Iupac::A], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstUI", recognition: &[Iupac::C, Iupac::G, Iupac::C, Iupac::G], top_offset: 2, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstV1I", recognition: &[Iupac::G, Iupac::C, Iupac::A, Iupac::G, Iupac::C], top_offset: 13, bottom_offset: 17, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BstV2I", recognition: &[Iupac::G, Iupac::A, Iupac::A, Iupac::G, Iupac::A, Iupac::C], top_offset: 8, bottom_offset: 12, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BstX2I", recognition: &[Iupac::R, Iupac::G, Iupac::A, Iupac::T, Iupac::C, Iupac::Y], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstXI", recognition: &[Iupac::C, Iupac::C, Iupac::A, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::T, Iupac::G, Iupac::G], top_offset: 8, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstYI", recognition: &[Iupac::R, Iupac::G, Iupac::A, Iupac::T, Iupac::C, Iupac::Y], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstZ17I", recognition: &[Iupac::G, Iupac::T, Iupac::A, Iupac::T, Iupac::A, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BstZI", recognition: &[Iupac::C, Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bsu15I", recognition: &[Iupac::A, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::T], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Bsu36I", recognition: &[Iupac::C, Iupac::C, Iupac::T, Iupac::N, Iupac::A, Iupac::G, Iupac::G], top_offset: 2, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BsuI", recognition: &[Iupac::G, Iupac::T, Iupac::A, Iupac::T, Iupac::C, Iupac::C], top_offset: 12, bottom_offset: 11, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BsuRI", recognition: &[Iupac::G, Iupac::G, Iupac::C, Iupac::C], top_offset: 2, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BtgI", recognition: &[Iupac::C, Iupac::C, Iupac::R, Iupac::Y, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BtrI", recognition: &[Iupac::C, Iupac::A, Iupac::C, Iupac::G, Iupac::T, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BtsCI", recognition: &[Iupac::G, Iupac::G, Iupac::A, Iupac::T, Iupac::G], top_offset: 7, bottom_offset: 5, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BtsI", recognition: &[Iupac::G, Iupac::C, Iupac::A, Iupac::G, Iupac::T, Iupac::G], top_offset: 8, bottom_offset: 6, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BtsIMutI", recognition: &[Iupac::C, Iupac::A, Iupac::G, Iupac::T, Iupac::G], top_offset: 7, bottom_offset: 5, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "BtuMI", recognition: &[Iupac::T, Iupac::C, Iupac::G, Iupac::C, Iupac::G, Iupac::A], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "BveI", recognition: &[Iupac::A, Iupac::C, Iupac::C, Iupac::T, Iupac::G, Iupac::C], top_offset: 10, bottom_offset: 14, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "Cac8I", recognition: &[Iupac::G, Iupac::C, Iupac::N, Iupac::N, Iupac::G, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "CaiI", recognition: &[Iupac::C, Iupac::A, Iupac::G, Iupac::N, Iupac::N, Iupac::N, Iupac::C, Iupac::T, Iupac::G], top_offset: 6, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "CciI", recognition: &[Iupac::T, Iupac::C, Iupac::A, Iupac::T, Iupac::G, Iupac::A], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "CciNI", recognition: &[Iupac::G, Iupac::C, Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::G, Iupac::C], top_offset: 2, bottom_offset: 6, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "CelII", recognition: &[Iupac::G, Iupac::C, Iupac::T, Iupac::N, Iupac::A, Iupac::G, Iupac::C], top_offset: 2, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "CfoI", recognition: &[Iupac::G, Iupac::C, Iupac::G, Iupac::C], top_offset: 3, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Cfr10I", recognition: &[Iupac::R, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::Y], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Cfr13I", recognition: &[Iupac::G, Iupac::G, Iupac::N, Iupac::C, Iupac::C], top_offset: 1, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Cfr42I", recognition: &[Iupac::C, Iupac::C, Iupac::G, Iupac::C, Iupac::G, Iupac::G], top_offset: 4, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Cfr9I", recognition: &[Iupac::C, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "ClaI", recognition: &[Iupac::A, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::T], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "CpoI", recognition: &[Iupac::C, Iupac::G, Iupac::G, Iupac::W, Iupac::C, Iupac::C, Iupac::G], top_offset: 2, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "CseI", recognition: &[Iupac::G, Iupac::A, Iupac::C, Iupac::G, Iupac::C], top_offset: 10, bottom_offset: 15, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "Csp45I", recognition: &[Iupac::T, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::A], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Csp6I", recognition: &[Iupac::G, Iupac::T, Iupac::A, Iupac::C], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "CspAI", recognition: &[Iupac::A, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::T], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "CspI", recognition: &[Iupac::C, Iupac::G, Iupac::G, Iupac::W, Iupac::C, Iupac::C, Iupac::G], top_offset: 2, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "CviJI", recognition: &[Iupac::R, Iupac::G, Iupac::C, Iupac::Y], top_offset: 2, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "CviKI-1", recognition: &[Iupac::R, Iupac::G, Iupac::C, Iupac::Y], top_offset: 2, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "CviQI", recognition: &[Iupac::G, Iupac::T, Iupac::A, Iupac::C], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "DdeI", recognition: &[Iupac::C, Iupac::T, Iupac::N, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "DinI", recognition: &[Iupac::G, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "DpnII", recognition: &[Iupac::G, Iupac::A, Iupac::T, Iupac::C], top_offset: 0, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "DraI", recognition: &[Iupac::T, Iupac::T, Iupac::T, Iupac::A, Iupac::A, Iupac::A], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "DraIII", recognition: &[Iupac::C, Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::T, Iupac::G], top_offset: 6, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "DrdI", recognition: &[Iupac::G, Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::T, Iupac::C], top_offset: 7, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "DriI", recognition: &[Iupac::G, Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::T, Iupac::C], top_offset: 6, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "DsaI", recognition: &[Iupac::C, Iupac::C, Iupac::R, Iupac::Y, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "DseDI", recognition: &[Iupac::G, Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::T, Iupac::C], top_offset: 7, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "EaeI", recognition: &[Iupac::Y, Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::R], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "EagI", recognition: &[Iupac::C, Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Eam1104I", recognition: &[Iupac::C, Iupac::T, Iupac::C, Iupac::T, Iupac::T, Iupac::C], top_offset: 7, bottom_offset: 10, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "Eam1105I", recognition: &[Iupac::G, Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::T, Iupac::C], top_offset: 6, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "EarI", recognition: &[Iupac::C, Iupac::T, Iupac::C, Iupac::T, Iupac::T, Iupac::C], top_offset: 7, bottom_offset: 10, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "EciI", recognition: &[Iupac::G, Iupac::G, Iupac::C, Iupac::G, Iupac::G, Iupac::A], top_offset: 17, bottom_offset: 15, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "Ecl136II", recognition: &[Iupac::G, Iupac::A, Iupac::G, Iupac::C, Iupac::T, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "EclHKI", recognition: &[Iupac::G, Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::T, Iupac::C], top_offset: 6, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Eco105I", recognition: &[Iupac::T, Iupac::A, Iupac::C, Iupac::G, Iupac::T, Iupac::A], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Eco130I", recognition: &[Iupac::C, Iupac::C, Iupac::W, Iupac::W, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Eco147I", recognition: &[Iupac::A, Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::T], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Eco24I", recognition: &[Iupac::G, Iupac::R, Iupac::G, Iupac::C, Iupac::Y, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Eco31I", recognition: &[Iupac::G, Iupac::G, Iupac::T, Iupac::C, Iupac::T, Iupac::C], top_offset: 7, bottom_offset: 11, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "Eco32I", recognition: &[Iupac::G, Iupac::A, Iupac::T, Iupac::A, Iupac::T, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Eco47I", recognition: &[Iupac::G, Iupac::G, Iupac::W, Iupac::C, Iupac::C], top_offset: 1, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Eco47III", recognition: &[Iupac::A, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::T], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Eco52I", recognition: &[Iupac::C, Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Eco53kI", recognition: &[Iupac::G, Iupac::A, Iupac::G, Iupac::C, Iupac::T, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Eco72I", recognition: &[Iupac::C, Iupac::A, Iupac::C, Iupac::G, Iupac::T, Iupac::G], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Eco81I", recognition: &[Iupac::C, Iupac::C, Iupac::T, Iupac::N, Iupac::A, Iupac::G, Iupac::G], top_offset: 2, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Eco88I", recognition: &[Iupac::C, Iupac::Y, Iupac::C, Iupac::G, Iupac::R, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Eco91I", recognition: &[Iupac::G, Iupac::G, Iupac::T, Iupac::N, Iupac::A, Iupac::C, Iupac::C], top_offset: 1, bottom_offset: 6, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "EcoICRI", recognition: &[Iupac::G, Iupac::A, Iupac::G, Iupac::C, Iupac::T, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "EcoNI", recognition: &[Iupac::C, Iupac::C, Iupac::T, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::A, Iupac::G, Iupac::G], top_offset: 5, bottom_offset: 6, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "EcoO109I", recognition: &[Iupac::R, Iupac::G, Iupac::G, Iupac::N, Iupac::C, Iupac::C, Iupac::Y], top_offset: 2, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "EcoRI", recognition: &[Iupac::G, Iupac::A, Iupac::A, Iupac::T, Iupac::T, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "EcoRII", recognition: &[Iupac::C, Iupac::C, Iupac::W, Iupac::G, Iupac::G], top_offset: 0, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "EcoRV", recognition: &[Iupac::G, Iupac::A, Iupac::T, Iupac::A, Iupac::T, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "EcoT38I", recognition: &[Iupac::G, Iupac::R, Iupac::G, Iupac::C, Iupac::Y, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "EgeI", recognition: &[Iupac::G, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "EheI", recognition: &[Iupac::G, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "ErhI", recognition: &[Iupac::C, Iupac::C, Iupac::W, Iupac::W, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Esp3I", recognition: &[Iupac::C, Iupac::G, Iupac::T, Iupac::C, Iupac::T, Iupac::C], top_offset: 7, bottom_offset: 11, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "FaeI", recognition: &[Iupac::C, Iupac::A, Iupac::T, Iupac::G], top_offset: 4, bottom_offset: 0, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "FaiI", recognition: &[Iupac::Y, Iupac::A, Iupac::T, Iupac::R], top_offset: 2, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "FalI", recognition: &[Iupac::A, Iupac::A, Iupac::G, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::C, Iupac::T, Iupac::T], top_offset: 24, bottom_offset: 19, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "FaqI", recognition: &[Iupac::G, Iupac::G, Iupac::G, Iupac::A, Iupac::C], top_offset: 15, bottom_offset: 19, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "FatI", recognition: &[Iupac::C, Iupac::A, Iupac::T, Iupac::G], top_offset: 0, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "FauI", recognition: &[Iupac::C, Iupac::C, Iupac::C, Iupac::G, Iupac::C], top_offset: 9, bottom_offset: 11, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "FauNDI", recognition: &[Iupac::C, Iupac::A, Iupac::T, Iupac::A, Iupac::T, Iupac::G], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "FblI", recognition: &[Iupac::G, Iupac::T, Iupac::M, Iupac::K, Iupac::A, Iupac::C], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Fnu4HI", recognition: &[Iupac::G, Iupac::C, Iupac::N, Iupac::G, Iupac::C], top_offset: 2, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "FokI", recognition: &[Iupac::G, Iupac::G, Iupac::A, Iupac::T, Iupac::G], top_offset: 14, bottom_offset: 18, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "FriOI", recognition: &[Iupac::G, Iupac::R, Iupac::G, Iupac::C, Iupac::Y, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "FseI", recognition: &[Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::C, Iupac::C], top_offset: 6, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Fsp4HI", recognition: &[Iupac::G, Iupac::C, Iupac::N, Iupac::G, Iupac::C], top_offset: 2, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "FspAI", recognition: &[Iupac::R, Iupac::T, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::A, Iupac::Y], top_offset: 4, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "FspBI", recognition: &[Iupac::C, Iupac::T, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "FspI", recognition: &[Iupac::T, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::A], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "GsaI", recognition: &[Iupac::C, Iupac::C, Iupac::C, Iupac::A, Iupac::G, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "GsuI", recognition: &[Iupac::C, Iupac::T, Iupac::G, Iupac::G, Iupac::A, Iupac::G], top_offset: 22, bottom_offset: 20, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "HaeII", recognition: &[Iupac::R, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::Y], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "HaeIII", recognition: &[Iupac::G, Iupac::G, Iupac::C, Iupac::C], top_offset: 2, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "HgaI", recognition: &[Iupac::G, Iupac::A, Iupac::C, Iupac::G, Iupac::C], top_offset: 10, bottom_offset: 15, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "HhaI", recognition: &[Iupac::G, Iupac::C, Iupac::G, Iupac::C], top_offset: 3, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Hin1I", recognition: &[Iupac::G, Iupac::R, Iupac::C, Iupac::G, Iupac::Y, Iupac::C], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Hin1II", recognition: &[Iupac::C, Iupac::A, Iupac::T, Iupac::G], top_offset: 4, bottom_offset: 0, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Hin6I", recognition: &[Iupac::G, Iupac::C, Iupac::G, Iupac::C], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "HinP1I", recognition: &[Iupac::G, Iupac::C, Iupac::G, Iupac::C], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "HincII", recognition: &[Iupac::G, Iupac::T, Iupac::Y, Iupac::R, Iupac::A, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "HindII", recognition: &[Iupac::G, Iupac::T, Iupac::Y, Iupac::R, Iupac::A, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "HindIII", recognition: &[Iupac::A, Iupac::A, Iupac::G, Iupac::C, Iupac::T, Iupac::T], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "HinfI", recognition: &[Iupac::G, Iupac::A, Iupac::N, Iupac::T, Iupac::C], top_offset: 1, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "HpaI", recognition: &[Iupac::G, Iupac::T, Iupac::T, Iupac::A, Iupac::A, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "HpaII", recognition: &[Iupac::C, Iupac::C, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "HphI", recognition: &[Iupac::G, Iupac::G, Iupac::T, Iupac::G, Iupac::A], top_offset: 13, bottom_offset: 12, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "Hpy166II", recognition: &[Iupac::G, Iupac::T, Iupac::N, Iupac::N, Iupac::A, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Hpy188I", recognition: &[Iupac::T, Iupac::C, Iupac::N, Iupac::G, Iupac::A], top_offset: 3, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Hpy188III", recognition: &[Iupac::T, Iupac::C, Iupac::N, Iupac::N, Iupac::G, Iupac::A], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Hpy8I", recognition: &[Iupac::G, Iupac::T, Iupac::N, Iupac::N, Iupac::A, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Hpy99I", recognition: &[Iupac::C, Iupac::G, Iupac::W, Iupac::C, Iupac::G], top_offset: 5, bottom_offset: 0, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "HpyAV", recognition: &[Iupac::C, Iupac::C, Iupac::T, Iupac::T, Iupac::C], top_offset: 11, bottom_offset: 10, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "HpyCH4III", recognition: &[Iupac::A, Iupac::C, Iupac::N, Iupac::G, Iupac::T], top_offset: 3, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "HpyCH4IV", recognition: &[Iupac::A, Iupac::C, Iupac::G, Iupac::T], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "HpyCH4V", recognition: &[Iupac::T, Iupac::G, Iupac::C, Iupac::A], top_offset: 2, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "HpyF10VI", recognition: &[Iupac::G, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::C], top_offset: 7, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "HpyF3I", recognition: &[Iupac::C, Iupac::T, Iupac::N, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "HpySE526I", recognition: &[Iupac::A, Iupac::C, Iupac::G, Iupac::T], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Hsp92I", recognition: &[Iupac::G, Iupac::R, Iupac::C, Iupac::G, Iupac::Y, Iupac::C], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Hsp92II", recognition: &[Iupac::C, Iupac::A, Iupac::T, Iupac::G], top_offset: 4, bottom_offset: 0, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "HspAI", recognition: &[Iupac::G, Iupac::C, Iupac::G, Iupac::C], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "KasI", recognition: &[Iupac::G, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Kpn2I", recognition: &[Iupac::T, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::A], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "KpnI", recognition: &[Iupac::G, Iupac::G, Iupac::T, Iupac::A, Iupac::C, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "KroNI", recognition: &[Iupac::G, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Ksp22I", recognition: &[Iupac::T, Iupac::G, Iupac::A, Iupac::T, Iupac::C, Iupac::A], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "KspAI", recognition: &[Iupac::G, Iupac::T, Iupac::T, Iupac::A, Iupac::A, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "KspI", recognition: &[Iupac::C, Iupac::C, Iupac::G, Iupac::C, Iupac::G, Iupac::G], top_offset: 4, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Kzo9I", recognition: &[Iupac::G, Iupac::A, Iupac::T, Iupac::C], top_offset: 0, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "LguI", recognition: &[Iupac::G, Iupac::C, Iupac::T, Iupac::C, Iupac::T, Iupac::T, Iupac::C], top_offset: 8, bottom_offset: 11, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "LmnI", recognition: &[Iupac::G, Iupac::C, Iupac::T, Iupac::C, Iupac::C], top_offset: 6, bottom_offset: 4, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "Lsp1109I", recognition: &[Iupac::G, Iupac::C, Iupac::A, Iupac::G, Iupac::C], top_offset: 13, bottom_offset: 17, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "LweI", recognition: &[Iupac::G, Iupac::C, Iupac::A, Iupac::T, Iupac::C], top_offset: 10, bottom_offset: 14, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "MabI", recognition: &[Iupac::A, Iupac::C, Iupac::C, Iupac::W, Iupac::G, Iupac::G, Iupac::T], top_offset: 1, bottom_offset: 6, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MamI", recognition: &[Iupac::G, Iupac::A, Iupac::T, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::A, Iupac::T, Iupac::C], top_offset: 5, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MauBI", recognition: &[Iupac::C, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::G], top_offset: 2, bottom_offset: 6, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MbiI", recognition: &[Iupac::C, Iupac::C, Iupac::G, Iupac::C, Iupac::T, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "MboI", recognition: &[Iupac::G, Iupac::A, Iupac::T, Iupac::C], top_offset: 0, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MboII", recognition: &[Iupac::G, Iupac::A, Iupac::A, Iupac::G, Iupac::A], top_offset: 13, bottom_offset: 12, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "MfeI", recognition: &[Iupac::C, Iupac::A, Iupac::A, Iupac::T, Iupac::T, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MhlI", recognition: &[Iupac::G, Iupac::D, Iupac::G, Iupac::C, Iupac::H, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MlsI", recognition: &[Iupac::T, Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::A], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MluCI", recognition: &[Iupac::A, Iupac::A, Iupac::T, Iupac::T], top_offset: 0, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MluI", recognition: &[Iupac::A, Iupac::C, Iupac::G, Iupac::C, Iupac::G, Iupac::T], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Mly113I", recognition: &[Iupac::G, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::C], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MlyI", recognition: &[Iupac::G, Iupac::A, Iupac::G, Iupac::T, Iupac::C], top_offset: 10, bottom_offset: 10, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "MnlI", recognition: &[Iupac::C, Iupac::C, Iupac::T, Iupac::C], top_offset: 11, bottom_offset: 10, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "Mox20I", recognition: &[Iupac::T, Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::A], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Mph1103I", recognition: &[Iupac::A, Iupac::T, Iupac::G, Iupac::C, Iupac::A, Iupac::T], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MreI", recognition: &[Iupac::C, Iupac::G, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::C, Iupac::G], top_offset: 2, bottom_offset: 6, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MroI", recognition: &[Iupac::T, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::A], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MroNI", recognition: &[Iupac::G, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MroXI", recognition: &[Iupac::G, Iupac::A, Iupac::A, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::T, Iupac::T, Iupac::C], top_offset: 5, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MscI", recognition: &[Iupac::T, Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::A], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MseI", recognition: &[Iupac::T, Iupac::T, Iupac::A, Iupac::A], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MslI", recognition: &[Iupac::C, Iupac::A, Iupac::Y, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::R, Iupac::T, Iupac::G], top_offset: 5, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Msp20I", recognition: &[Iupac::T, Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::A], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MspA1I", recognition: &[Iupac::C, Iupac::M, Iupac::G, Iupac::C, Iupac::K, Iupac::G], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MspCI", recognition: &[Iupac::C, Iupac::T, Iupac::T, Iupac::A, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MspI", recognition: &[Iupac::C, Iupac::C, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MspR9I", recognition: &[Iupac::C, Iupac::C, Iupac::N, Iupac::G, Iupac::G], top_offset: 2, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MssI", recognition: &[Iupac::G, Iupac::T, Iupac::T, Iupac::T, Iupac::A, Iupac::A, Iupac::A, Iupac::C], top_offset: 4, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MunI", recognition: &[Iupac::C, Iupac::A, Iupac::A, Iupac::T, Iupac::T, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Mva1269I", recognition: &[Iupac::G, Iupac::A, Iupac::A, Iupac::T, Iupac::G, Iupac::C], top_offset: 7, bottom_offset: 5, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "MvaI", recognition: &[Iupac::C, Iupac::C, Iupac::W, Iupac::G, Iupac::G], top_offset: 2, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "MwoI", recognition: &[Iupac::G, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::C], top_offset: 7, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "NaeI", recognition: &[Iupac::G, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "NarI", recognition: &[Iupac::G, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::C], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "NciI", recognition: &[Iupac::C, Iupac::C, Iupac::S, Iupac::G, Iupac::G], top_offset: 2, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "NcoI", recognition: &[Iupac::C, Iupac::C, Iupac::A, Iupac::T, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "NdeI", recognition: &[Iupac::C, Iupac::A, Iupac::T, Iupac::A, Iupac::T, Iupac::G], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "NdeII", recognition: &[Iupac::G, Iupac::A, Iupac::T, Iupac::C], top_offset: 0, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "NgoMIV", recognition: &[Iupac::G, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "NheI", recognition: &[Iupac::G, Iupac::C, Iupac::T, Iupac::A, Iupac::G, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "NlaIII", recognition: &[Iupac::C, Iupac::A, Iupac::T, Iupac::G], top_offset: 4, bottom_offset: 0, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "NlaIV", recognition: &[Iupac::G, Iupac::G, Iupac::N, Iupac::N, Iupac::C, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "NmuCI", recognition: &[Iupac::G, Iupac::T, Iupac::S, Iupac::A, Iupac::C], top_offset: 0, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "NotI", recognition: &[Iupac::G, Iupac::C, Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::G, Iupac::C], top_offset: 2, bottom_offset: 6, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "NruI", recognition: &[Iupac::T, Iupac::C, Iupac::G, Iupac::C, Iupac::G, Iupac::A], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "NsbI", recognition: &[Iupac::T, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::A], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "NsiI", recognition: &[Iupac::A, Iupac::T, Iupac::G, Iupac::C, Iupac::A, Iupac::T], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "NspI", recognition: &[Iupac::R, Iupac::C, Iupac::A, Iupac::T, Iupac::G, Iupac::Y], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "NspV", recognition: &[Iupac::T, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::A], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "OliI", recognition: &[Iupac::C, Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::T, Iupac::G], top_offset: 5, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PacI", recognition: &[Iupac::T, Iupac::T, Iupac::A, Iupac::A, Iupac::T, Iupac::T, Iupac::A, Iupac::A], top_offset: 5, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PaeI", recognition: &[Iupac::G, Iupac::C, Iupac::A, Iupac::T, Iupac::G, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PaeR7I", recognition: &[Iupac::C, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PagI", recognition: &[Iupac::T, Iupac::C, Iupac::A, Iupac::T, Iupac::G, Iupac::A], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PalAI", recognition: &[Iupac::G, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::C], top_offset: 2, bottom_offset: 6, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PaqCI", recognition: &[Iupac::C, Iupac::A, Iupac::C, Iupac::C, Iupac::T, Iupac::G, Iupac::C], top_offset: 11, bottom_offset: 15, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "PasI", recognition: &[Iupac::C, Iupac::C, Iupac::C, Iupac::W, Iupac::G, Iupac::G, Iupac::G], top_offset: 2, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PauI", recognition: &[Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::G, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PceI", recognition: &[Iupac::A, Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::T], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PciI", recognition: &[Iupac::A, Iupac::C, Iupac::A, Iupac::T, Iupac::G, Iupac::T], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PciSI", recognition: &[Iupac::G, Iupac::C, Iupac::T, Iupac::C, Iupac::T, Iupac::T, Iupac::C], top_offset: 8, bottom_offset: 11, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "PctI", recognition: &[Iupac::G, Iupac::A, Iupac::A, Iupac::T, Iupac::G, Iupac::C], top_offset: 7, bottom_offset: 5, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "PdiI", recognition: &[Iupac::G, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PdmI", recognition: &[Iupac::G, Iupac::A, Iupac::A, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::T, Iupac::T, Iupac::C], top_offset: 5, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PecI", recognition: &[Iupac::T, Iupac::T, Iupac::A, Iupac::T, Iupac::A, Iupac::A], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PfeI", recognition: &[Iupac::G, Iupac::A, Iupac::W, Iupac::T, Iupac::C], top_offset: 1, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Pfl23II", recognition: &[Iupac::C, Iupac::G, Iupac::T, Iupac::A, Iupac::C, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PflFI", recognition: &[Iupac::G, Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::T, Iupac::C], top_offset: 4, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PflMI", recognition: &[Iupac::C, Iupac::C, Iupac::A, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::T, Iupac::G, Iupac::G], top_offset: 7, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PfoI", recognition: &[Iupac::T, Iupac::C, Iupac::C, Iupac::N, Iupac::G, Iupac::G, Iupac::A], top_offset: 1, bottom_offset: 6, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PinAI", recognition: &[Iupac::A, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::T], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Ple19I", recognition: &[Iupac::C, Iupac::G, Iupac::A, Iupac::T, Iupac::C, Iupac::G], top_offset: 4, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PleI", recognition: &[Iupac::G, Iupac::A, Iupac::G, Iupac::T, Iupac::C], top_offset: 9, bottom_offset: 10, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "PluTI", recognition: &[Iupac::G, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PmeI", recognition: &[Iupac::G, Iupac::T, Iupac::T, Iupac::T, Iupac::A, Iupac::A, Iupac::A, Iupac::C], top_offset: 4, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PmlI", recognition: &[Iupac::C, Iupac::A, Iupac::C, Iupac::G, Iupac::T, Iupac::G], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PpsI", recognition: &[Iupac::G, Iupac::A, Iupac::G, Iupac::T, Iupac::C], top_offset: 9, bottom_offset: 10, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "Ppu21I", recognition: &[Iupac::Y, Iupac::A, Iupac::C, Iupac::G, Iupac::T, Iupac::R], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PpuMI", recognition: &[Iupac::R, Iupac::G, Iupac::G, Iupac::W, Iupac::C, Iupac::C, Iupac::Y], top_offset: 2, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PscI", recognition: &[Iupac::A, Iupac::C, Iupac::A, Iupac::T, Iupac::G, Iupac::T], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Pse31I", recognition: &[Iupac::G, Iupac::G, Iupac::T, Iupac::C, Iupac::T, Iupac::C], top_offset: 7, bottom_offset: 11, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "PshAI", recognition: &[Iupac::G, Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::T, Iupac::C], top_offset: 5, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PsiI", recognition: &[Iupac::T, Iupac::T, Iupac::A, Iupac::T, Iupac::A, Iupac::A], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Psp124BI", recognition: &[Iupac::G, Iupac::A, Iupac::G, Iupac::C, Iupac::T, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Psp1406I", recognition: &[Iupac::A, Iupac::A, Iupac::C, Iupac::G, Iupac::T, Iupac::T], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Psp5II", recognition: &[Iupac::R, Iupac::G, Iupac::G, Iupac::W, Iupac::C, Iupac::C, Iupac::Y], top_offset: 2, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Psp6I", recognition: &[Iupac::C, Iupac::C, Iupac::W, Iupac::G, Iupac::G], top_offset: 0, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PspCI", recognition: &[Iupac::C, Iupac::A, Iupac::C, Iupac::G, Iupac::T, Iupac::G], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PspEI", recognition: &[Iupac::G, Iupac::G, Iupac::T, Iupac::N, Iupac::A, Iupac::C, Iupac::C], top_offset: 1, bottom_offset: 6, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PspGI", recognition: &[Iupac::C, Iupac::C, Iupac::W, Iupac::G, Iupac::G], top_offset: 0, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PspLI", recognition: &[Iupac::C, Iupac::G, Iupac::T, Iupac::A, Iupac::C, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PspN4I", recognition: &[Iupac::G, Iupac::G, Iupac::N, Iupac::N, Iupac::C, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PspOMI", recognition: &[Iupac::G, Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PspPI", recognition: &[Iupac::G, Iupac::G, Iupac::N, Iupac::C, Iupac::C], top_offset: 1, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PspPPI", recognition: &[Iupac::R, Iupac::G, Iupac::G, Iupac::W, Iupac::C, Iupac::C, Iupac::Y], top_offset: 2, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PspXI", recognition: &[Iupac::V, Iupac::C, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::G, Iupac::B], top_offset: 2, bottom_offset: 6, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PsrI", recognition: &[Iupac::G, Iupac::A, Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::T, Iupac::A, Iupac::C], top_offset: 25, bottom_offset: 20, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "PstI", recognition: &[Iupac::C, Iupac::T, Iupac::G, Iupac::C, Iupac::A, Iupac::G], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PstNI", recognition: &[Iupac::C, Iupac::A, Iupac::G, Iupac::N, Iupac::N, Iupac::N, Iupac::C, Iupac::T, Iupac::G], top_offset: 6, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PsuI", recognition: &[Iupac::R, Iupac::G, Iupac::A, Iupac::T, Iupac::C, Iupac::Y], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PsyI", recognition: &[Iupac::G, Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::T, Iupac::C], top_offset: 4, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PvuI", recognition: &[Iupac::C, Iupac::G, Iupac::A, Iupac::T, Iupac::C, Iupac::G], top_offset: 4, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "PvuII", recognition: &[Iupac::C, Iupac::A, Iupac::G, Iupac::C, Iupac::T, Iupac::G], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "RgaI", recognition: &[Iupac::G, Iupac::C, Iupac::G, Iupac::A, Iupac::T, Iupac::C, Iupac::G, Iupac::C], top_offset: 5, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "RigI", recognition: &[Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::C, Iupac::C], top_offset: 6, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "RsaI", recognition: &[Iupac::G, Iupac::T, Iupac::A, Iupac::C], top_offset: 2, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "RsaNI", recognition: &[Iupac::G, Iupac::T, Iupac::A, Iupac::C], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "RseI", recognition: &[Iupac::C, Iupac::A, Iupac::Y, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::R, Iupac::T, Iupac::G], top_offset: 5, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Rsr2I", recognition: &[Iupac::C, Iupac::G, Iupac::G, Iupac::W, Iupac::C, Iupac::C, Iupac::G], top_offset: 2, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "RsrII", recognition: &[Iupac::C, Iupac::G, Iupac::G, Iupac::W, Iupac::C, Iupac::C, Iupac::G], top_offset: 2, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SacI", recognition: &[Iupac::G, Iupac::A, Iupac::G, Iupac::C, Iupac::T, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SacII", recognition: &[Iupac::C, Iupac::C, Iupac::G, Iupac::C, Iupac::G, Iupac::G], top_offset: 4, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SalI", recognition: &[Iupac::G, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SapI", recognition: &[Iupac::G, Iupac::C, Iupac::T, Iupac::C, Iupac::T, Iupac::T, Iupac::C], top_offset: 8, bottom_offset: 11, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "SatI", recognition: &[Iupac::G, Iupac::C, Iupac::N, Iupac::G, Iupac::C], top_offset: 2, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Sau3AI", recognition: &[Iupac::G, Iupac::A, Iupac::T, Iupac::C], top_offset: 0, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Sau96I", recognition: &[Iupac::G, Iupac::G, Iupac::N, Iupac::C, Iupac::C], top_offset: 1, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SbfI", recognition: &[Iupac::C, Iupac::C, Iupac::T, Iupac::G, Iupac::C, Iupac::A, Iupac::G, Iupac::G], top_offset: 6, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "ScaI", recognition: &[Iupac::A, Iupac::G, Iupac::T, Iupac::A, Iupac::C, Iupac::T], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SchI", recognition: &[Iupac::G, Iupac::A, Iupac::G, Iupac::T, Iupac::C], top_offset: 10, bottom_offset: 10, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "ScrFI", recognition: &[Iupac::C, Iupac::C, Iupac::N, Iupac::G, Iupac::G], top_offset: 2, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SdaI", recognition: &[Iupac::C, Iupac::C, Iupac::T, Iupac::G, Iupac::C, Iupac::A, Iupac::G, Iupac::G], top_offset: 6, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SduI", recognition: &[Iupac::G, Iupac::D, Iupac::G, Iupac::C, Iupac::H, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SetI", recognition: &[Iupac::A, Iupac::S, Iupac::S, Iupac::T], top_offset: 4, bottom_offset: 0, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SexAI", recognition: &[Iupac::A, Iupac::C, Iupac::C, Iupac::W, Iupac::G, Iupac::G, Iupac::T], top_offset: 1, bottom_offset: 6, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SfaAI", recognition: &[Iupac::G, Iupac::C, Iupac::G, Iupac::A, Iupac::T, Iupac::C, Iupac::G, Iupac::C], top_offset: 5, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SfaNI", recognition: &[Iupac::G, Iupac::C, Iupac::A, Iupac::T, Iupac::C], top_offset: 10, bottom_offset: 14, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "SfcI", recognition: &[Iupac::C, Iupac::T, Iupac::R, Iupac::Y, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SfiI", recognition: &[Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::G, Iupac::C, Iupac::C], top_offset: 8, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SfoI", recognition: &[Iupac::G, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Sfr274I", recognition: &[Iupac::C, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Sfr303I", recognition: &[Iupac::C, Iupac::C, Iupac::G, Iupac::C, Iupac::G, Iupac::G], top_offset: 4, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SfuI", recognition: &[Iupac::T, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::A], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SgfI", recognition: &[Iupac::G, Iupac::C, Iupac::G, Iupac::A, Iupac::T, Iupac::C, Iupac::G, Iupac::C], top_offset: 5, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SgrAI", recognition: &[Iupac::C, Iupac::R, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::Y, Iupac::G], top_offset: 2, bottom_offset: 6, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SgrBI", recognition: &[Iupac::C, Iupac::C, Iupac::G, Iupac::C, Iupac::G, Iupac::G], top_offset: 4, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SgrDI", recognition: &[Iupac::C, Iupac::G, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::C, Iupac::G], top_offset: 2, bottom_offset: 6, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SgsI", recognition: &[Iupac::G, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::C], top_offset: 2, bottom_offset: 6, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SinI", recognition: &[Iupac::G, Iupac::G, Iupac::W, Iupac::C, Iupac::C], top_offset: 1, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SlaI", recognition: &[Iupac::C, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SmaI", recognition: &[Iupac::C, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::G], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SmiI", recognition: &[Iupac::A, Iupac::T, Iupac::T, Iupac::T, Iupac::A, Iupac::A, Iupac::A, Iupac::T], top_offset: 4, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SmiMI", recognition: &[Iupac::C, Iupac::A, Iupac::Y, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::R, Iupac::T, Iupac::G], top_offset: 5, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SmlI", recognition: &[Iupac::C, Iupac::T, Iupac::Y, Iupac::R, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SmoI", recognition: &[Iupac::C, Iupac::T, Iupac::Y, Iupac::R, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SnaBI", recognition: &[Iupac::T, Iupac::A, Iupac::C, Iupac::G, Iupac::T, Iupac::A], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SpeI", recognition: &[Iupac::A, Iupac::C, Iupac::T, Iupac::A, Iupac::G, Iupac::T], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SphI", recognition: &[Iupac::G, Iupac::C, Iupac::A, Iupac::T, Iupac::G, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SrfI", recognition: &[Iupac::G, Iupac::C, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::G, Iupac::C], top_offset: 4, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Sse9I", recognition: &[Iupac::A, Iupac::A, Iupac::T, Iupac::T], top_offset: 0, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SseBI", recognition: &[Iupac::A, Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::T], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SsiI", recognition: &[Iupac::C, Iupac::C, Iupac::G, Iupac::C], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "SspDI", recognition: &[Iupac::G, Iupac::G, Iupac::C, Iupac::G, Iupac::C, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SspI", recognition: &[Iupac::A, Iupac::A, Iupac::T, Iupac::A, Iupac::T, Iupac::T], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SspMI", recognition: &[Iupac::C, Iupac::T, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SstI", recognition: &[Iupac::G, Iupac::A, Iupac::G, Iupac::C, Iupac::T, Iupac::C], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "StuI", recognition: &[Iupac::A, Iupac::G, Iupac::G, Iupac::C, Iupac::C, Iupac::T], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "StyD4I", recognition: &[Iupac::C, Iupac::C, Iupac::N, Iupac::G, Iupac::G], top_offset: 0, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "StyI", recognition: &[Iupac::C, Iupac::C, Iupac::W, Iupac::W, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "SwaI", recognition: &[Iupac::A, Iupac::T, Iupac::T, Iupac::T, Iupac::A, Iupac::A, Iupac::A, Iupac::T], top_offset: 4, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "TaaI", recognition: &[Iupac::A, Iupac::C, Iupac::N, Iupac::G, Iupac::T], top_offset: 3, bottom_offset: 2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "TaiI", recognition: &[Iupac::A, Iupac::C, Iupac::G, Iupac::T], top_offset: 4, bottom_offset: 0, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "TaqI", recognition: &[Iupac::T, Iupac::C, Iupac::G, Iupac::A], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "TasI", recognition: &[Iupac::A, Iupac::A, Iupac::T, Iupac::T], top_offset: 0, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "TatI", recognition: &[Iupac::W, Iupac::G, Iupac::T, Iupac::A, Iupac::C, Iupac::W], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "TauI", recognition: &[Iupac::G, Iupac::C, Iupac::S, Iupac::G, Iupac::C], top_offset: 4, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "TfiI", recognition: &[Iupac::G, Iupac::A, Iupac::W, Iupac::T, Iupac::C], top_offset: 1, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Tru1I", recognition: &[Iupac::T, Iupac::T, Iupac::A, Iupac::A], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Tru9I", recognition: &[Iupac::T, Iupac::T, Iupac::A, Iupac::A], top_offset: 1, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "TscAI", recognition: &[Iupac::C, Iupac::A, Iupac::S, Iupac::T, Iupac::G], top_offset: 7, bottom_offset: -2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "TseFI", recognition: &[Iupac::G, Iupac::T, Iupac::S, Iupac::A, Iupac::C], top_offset: 0, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "TseI", recognition: &[Iupac::G, Iupac::C, Iupac::W, Iupac::G, Iupac::C], top_offset: 1, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Tsp45I", recognition: &[Iupac::G, Iupac::T, Iupac::S, Iupac::A, Iupac::C], top_offset: 0, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "TspDTI", recognition: &[Iupac::A, Iupac::T, Iupac::G, Iupac::A, Iupac::A], top_offset: 16, bottom_offset: 14, enzyme_type: EnzymeType::TypeIIs },
    Enzyme { name: "TspMI", recognition: &[Iupac::C, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "TspRI", recognition: &[Iupac::C, Iupac::A, Iupac::S, Iupac::T, Iupac::G], top_offset: 7, bottom_offset: -2, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Tth111I", recognition: &[Iupac::G, Iupac::A, Iupac::C, Iupac::N, Iupac::N, Iupac::N, Iupac::G, Iupac::T, Iupac::C], top_offset: 4, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Van91I", recognition: &[Iupac::C, Iupac::C, Iupac::A, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::T, Iupac::G, Iupac::G], top_offset: 7, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Vha464I", recognition: &[Iupac::C, Iupac::T, Iupac::T, Iupac::A, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "VneI", recognition: &[Iupac::G, Iupac::T, Iupac::G, Iupac::C, Iupac::A, Iupac::C], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "VspI", recognition: &[Iupac::A, Iupac::T, Iupac::T, Iupac::A, Iupac::A, Iupac::T], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "XagI", recognition: &[Iupac::C, Iupac::C, Iupac::T, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::A, Iupac::G, Iupac::G], top_offset: 5, bottom_offset: 6, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "XapI", recognition: &[Iupac::R, Iupac::A, Iupac::A, Iupac::T, Iupac::T, Iupac::Y], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "XbaI", recognition: &[Iupac::T, Iupac::C, Iupac::T, Iupac::A, Iupac::G, Iupac::A], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "XceI", recognition: &[Iupac::R, Iupac::C, Iupac::A, Iupac::T, Iupac::G, Iupac::Y], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "XcmI", recognition: &[Iupac::C, Iupac::C, Iupac::A, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::T, Iupac::G, Iupac::G], top_offset: 8, bottom_offset: 7, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "XhoI", recognition: &[Iupac::C, Iupac::T, Iupac::C, Iupac::G, Iupac::A, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "XhoII", recognition: &[Iupac::R, Iupac::G, Iupac::A, Iupac::T, Iupac::C, Iupac::Y], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "XmaCI", recognition: &[Iupac::C, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "XmaI", recognition: &[Iupac::C, Iupac::C, Iupac::C, Iupac::G, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "XmaJI", recognition: &[Iupac::C, Iupac::C, Iupac::T, Iupac::A, Iupac::G, Iupac::G], top_offset: 1, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "XmiI", recognition: &[Iupac::G, Iupac::T, Iupac::M, Iupac::K, Iupac::A, Iupac::C], top_offset: 2, bottom_offset: 4, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "XmnI", recognition: &[Iupac::G, Iupac::A, Iupac::A, Iupac::N, Iupac::N, Iupac::N, Iupac::N, Iupac::T, Iupac::T, Iupac::C], top_offset: 5, bottom_offset: 5, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "ZraI", recognition: &[Iupac::G, Iupac::A, Iupac::C, Iupac::G, Iupac::T, Iupac::C], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "ZrmI", recognition: &[Iupac::A, Iupac::G, Iupac::T, Iupac::A, Iupac::C, Iupac::T], top_offset: 3, bottom_offset: 3, enzyme_type: EnzymeType::TypeII },
    Enzyme { name: "Zsp2I", recognition: &[Iupac::A, Iupac::T, Iupac::G, Iupac::C, Iupac::A, Iupac::T], top_offset: 5, bottom_offset: 1, enzyme_type: EnzymeType::TypeII },
];
